// Copyright 2017-2023 @polkadot/apps authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

<<<<<<< HEAD
export const packageInfo = { name: '@polkadot/apps', path: 'auto', type: 'auto', version: '0.129.2-0-x' };
=======
export const packageInfo = { name: '@polkadot/apps', path: 'auto', type: 'auto', version: '0.132.2-70-x' };
>>>>>>> ee79dc8ca86484d8700d24a4be0f001360f84b4f
